branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
language: minimal
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      before_install:
        - brew tap adoptopenjdk/openjdk
        - brew cask install adoptopenjdk11
        - brew install maven
        - brew install esolitos/ipa/sshpass
    - os: windows
      matrix:
        - JDK="openjdk@1.11.0-2"
      before_install:
        - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
        - source $GRAVIS/install-jdk
        - source $GRAVIS/install-maven
        - choco install putty
      cache:
        directories:
          - $HOME/.m2
          - $HOME/.jabba/
install:
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mvn clean package -DskipTests -P mac -B      ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mvn clean package -DskipTests -P win -B  ; fi
before_deploy:
  - export MAC_FILE_PATH=dist/mac/release/pdftrick_${TRAVIS_TAG:1}.dmg
  - export WIN_FILE_PATH=dist/win/release/pdftrick_${TRAVIS_TAG:1}.exe
deploy:
  #provider: script
  #skip_cleanup: true
  #script: bash ./deploy.sh
  #on:
    #tags: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - ${MAC_FILE_PATH}
    - ${WIN_FILE_PATH}
  skip_cleanup: true
    on:
      tags: true
