branches:
  only:
    - master
language: minimal

os:
  - windows
  - osx
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="openjdk@1.11.0-2"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - source $GRAVIS/install-maven

cache:
  directories:
    - $HOME/.m2
    - $HOME/.jabba/

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master